FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc python3-dev

COPY requirements.txt .
RUN pip install kafka-python requests numpy psutil

COPY src/generator.py .

CMD ["python", "generator.py"]
