FROM bitnami/spark:3.5.3

USER root
WORKDIR /app

# Install all required dependencies
RUN pip install kafka-python pyspark==3.5.3 requests numpy psutil pandas redis flask flask-cors websockets

# Create necessary directories
RUN mkdir -p /app/logs /root/.ivy2 && \
    chmod -R 777 /app/logs /root/.ivy2

# Copy source files
COPY src/consumer.py /app/
COPY src/api.py /app/
COPY src/index.html /app/

# Set proper permissions
RUN chmod -R 755 /app
