FROM bitnami/spark:3.5.3

USER root
WORKDIR /app

# Install all required dependencies
RUN pip install kafka-python pyspark==3.5.3 requests numpy psutil pandas redis flask websockets

# Create necessary directories
RUN mkdir -p /app/logs && \
    mkdir -p /root/.ivy2 && \
    chmod -R 777 /app/logs

# Keep container running and let deployment handle spark-submit
CMD ["tail", "-f", "/dev/null"]
