apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
  labels:
    app: spark-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      containers:
      - name: spark-consumer
        image: hosseinabedi/spark-consumer:lastest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.default.svc.cluster.local:9092"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        volumeMounts:
        - name: checkpoint-volume
          mountPath: /tmp/checkpoint
      volumes:
      - name: checkpoint-volume
        emptyDir: {}
