apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
  labels:
    app: spark-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      containers:
      - name: spark-consumer
        image: spark-consumer:latest  # Changed to use custom image
        ports:
        - containerPort: 8765  # WebSocket port
        - containerPort: 5000  # Flask API port
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: log-volume
          mountPath: /app/logs
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
        - name: REDIS_HOST
          value: "redis"
      volumes:
      - name: app-code
        hostPath:
          path: /c/Users/abedi/OneDrive/Documents/GitHub/DS-final-PJ/src
      - name: log-volume
        hostPath:
          path: /c/Users/abedi/OneDrive/Documents/GitHub/DS-final-PJ/logs
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: NodePort  # Change to NodePort to access WebSocket
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 5001  # Changed from 9092 to 5001
      targetPort: 5001  # Changed from 9092 to 5001
    - port: 5000
      targetPort: 5000
      nodePort: 30500  # API port
    - port: 8765
      targetPort: 8765
      nodePort: 30765  # External port for WebSocket
