apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  labels:
    app: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
      - name: generator
        image: data-generator:latest
        imagePullPolicy: IfNotPresent   # This ensures it uses the local image
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: generator-service
spec:
  selector:
    app: data-generator  # Updated to match deployment labels
  ports:
    - protocol: TCP
      port: 5000  # Changed from 9092 to 5000
      targetPort: 5000  # Changed from 9092 to 5000
