apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer:latest  # Use local image
        imagePullPolicy: IfNotPresent  # Use local image if available
        ports:
        - containerPort: 5001  # Changed from 9092 to 5001
        command: 
        - "spark-submit"
        - "--packages"
        - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3"  # Fixed to correct latest version
        - "--master"
        - "k8s://https://kubernetes.default.svc:443"
        - "/app/consumer.py"
        env:
        - name: SPARK_HOME
          value: "/opt/bitnami/spark"
        volumeMounts:
        - name: src-files
          mountPath: /app
      volumes:
      - name: src-files
        hostPath:
          path: /src
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 5001  # Changed from 9092 to 5001
      targetPort: 5001  # Changed from 9092 to 5001
