apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: mfary636/flask-api:v1.2 # Replace with your image
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: CONSUMER_URL
          value: "http://spark-consumer-service.default.svc.cluster.local:6001"
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30501  # Fixed NodePort for API
