apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
  labels:
    app: spark-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      containers:
      - name: spark-consumer
        image: mfary636/spark-consumer:v1.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6001
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.default.svc.cluster.local:9092"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: checkpoint-volume
          mountPath: /tmp/checkpoint
      volumes:
      - name: checkpoint-volume
        emptyDir: {}
      resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spark-consumer-service
spec:
  type: NodePort
  ports:
    - port: 6001
      targetPort: 6001
      nodePort: 30601
      protocol: TCP
  selector:
    app: spark-consumer
  
